<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "couple_manager"
 *
 * Auto generated by Extension Builder 2018-08-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Couple Manager',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sebastian Wilhelm',
    'author_email' => 'wilhelm79@web.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
